name: main

on:
  workflow_call:
    inputs:
      build-artifact-name:
        required: true
        type: string
      build-artifact-path:
        required: true
        type: string
      self-build:
        required: false
        type: number
      pyodide-versions:
        required: false
        type: string
        default: ""
      runners:
        required: false
        type: string
        default: ""
      browsers:
        required: false
        type: string
        default: ""
      os:
        required: false
        type: string
        default: ""
permissions:
  contents: read
jobs:
  make_test_matrix:
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build test matrix
        id: build-matrix
        run: |
          python .github/workflows/build_matrix.py \
            --pyodide-version ${{ inputs.pyodide-versions }} \
            --os ${{ inputs.os }} \
            --runner ${{ inputs.runners }} \
            --browser ${{ iputs.browsers }} \
            >> $GITHUB_OUTPUT
      - name: Output test matrix
        run: echo "Test matrix is ${{ steps.build-matrix.outputs.matrix }}"
  check_matrix:
    needs: make_test_matrix
    runs-on: ubuntu-latest
    steps:
      - name: show matrix
        run: echo "${{ needs.make_test_matrix.outputs.matrix }}"
  call-main-workflow:
    needs: make_test_matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.make_test_matrix.outputs.matrix) }}
    uses: ./.github/workflows/main.yaml
    with:
      build-artifact-name: ${{ inputs.build-artifact-name }}
      build-artifact-path: ${{ inputs.build-artifact-path }}
      self-build: ${{ inputs.self-build }}
      pyodide-version: ${{ matrix.pyodide-version }}
      runner: ${{ matrix.test-config.runner }}
      browser: ${{ matrix.test-config.browser }}
      os: ${{ matrix.os }}
      browser-version: ${{ matrix.test-config.browser-version }}
      driver-version: ${{ matrix.test-config.driver-version }}
      refresh: ${{ matrix.test-config.refresh }}
      runner-version: ${{ matrix.test-config.runner-version }}
